services:

  dnsdist:
    image: powerdns/dnsdist-19:latest
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf
      - ./ssl:/opt/certs
    ports:
      - "5053:53/udp"
      - "5053:53/tcp"
      - "443:443"
      - "853:853"
    networks:
      - webnet

networks:
  webnet:
